include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - "example/flutter_vehicle_app/**"
    - "example/flutter_drone_cockpit/**"

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
