#!/usr/bin/env python3
#
# capnp_dart_gen.py — Generate Dart FFI bindings from Cap'n Proto schemas.
#
# Usage:
#   python3 tools/capnp_dart_gen.py \
#       --schema-dir schemas/ \
#       --output-dir lib/generated/ \
#       [--force]
#
# For each .capnp file in --schema-dir, generates a *Reader and *Builder
# class with field accessors. Fixed-size scalar fields are packed in
# ordinal order with natural alignment; Text/Data fields go into a
# variable-length tail section after the fixed header.
#
# This is NOT a Cap'n Proto wire-format generator — it produces a thin
# layout that's stable across all schemas in this repo and matches what
# the C++ bridge's accessor functions expect. Real wire-format support
# would require pycapnp; this is intentionally dependency-free so it can
# run inside hooks/build.dart with only Python on PATH.
#
# Copyright (c) 2026 Joel Winarske. Apache 2.0 license.

import argparse
import re
import sys
from pathlib import Path

# Cap'n Proto type → (Dart return type, ByteData accessor suffix, byte size)
SCALAR_TYPES = {
    'Float32': ('double', 'Float32', 4),
    'Float64': ('double', 'Float64', 8),
    'UInt8':   ('int', 'Uint8', 1),
    'UInt16':  ('int', 'Uint16', 2),
    'UInt32':  ('int', 'Uint32', 4),
    'UInt64':  ('int', 'Uint64', 8),
    'Int8':    ('int', 'Int8', 1),
    'Int16':   ('int', 'Int16', 2),
    'Int32':   ('int', 'Int32', 4),
    'Int64':   ('int', 'Int64', 8),
}
BOOL_TYPE = 'Bool'
TEXT_TYPE = 'Text'
DATA_TYPE = 'Data'

FIELD_RE = re.compile(
    r'\s*(?P<name>\w+)\s*@(?P<ordinal>\d+)\s*:(?P<type>\w+)\s*[;#]'
)
STRUCT_RE = re.compile(r'struct\s+(?P<name>\w+)\s*\{')
ID_RE = re.compile(r'@0x([0-9a-fA-F]+)\s*;')


class Field:
    __slots__ = ('name', 'ordinal', 'capnp_type', 'offset')

    def __init__(self, name, ordinal, capnp_type):
        self.name = name
        self.ordinal = ordinal
        self.capnp_type = capnp_type
        self.offset = -1  # filled by layout()

    @property
    def is_scalar(self):
        return self.capnp_type in SCALAR_TYPES

    @property
    def is_bool(self):
        return self.capnp_type == BOOL_TYPE

    @property
    def is_text(self):
        return self.capnp_type == TEXT_TYPE

    @property
    def is_data(self):
        return self.capnp_type == DATA_TYPE

    @property
    def size(self):
        if self.is_scalar:
            return SCALAR_TYPES[self.capnp_type][2]
        if self.is_bool:
            return 1
        return 0  # text/data live in the variable section


def snake_to_camel(name):
    if '_' not in name:
        return name[0].lower() + name[1:]
    parts = name.split('_')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


def parse_schema(text):
    """Return (struct_name, schema_id_int, [Field, ...]) or None."""
    id_m = ID_RE.search(text)
    if not id_m:
        return None
    schema_id = int(id_m.group(1), 16) & 0xFFFF  # truncate to short id

    struct_m = STRUCT_RE.search(text)
    if not struct_m:
        return None
    struct_name = struct_m.group('name')

    # Body between braces — naive but adequate for these single-struct files.
    brace_start = struct_m.end() - 1
    depth = 0
    end = -1
    for i in range(brace_start, len(text)):
        c = text[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                end = i
                break
    if end < 0:
        return None
    body = text[brace_start + 1:end]

    fields = []
    for line in body.splitlines():
        m = FIELD_RE.match(line)
        if not m:
            continue
        fields.append(Field(m.group('name'), int(m.group('ordinal')),
                            m.group('type')))
    fields.sort(key=lambda f: f.ordinal)
    return struct_name, schema_id, fields


def layout(fields):
    """Pack scalar/bool fields with natural alignment. Returns header_len."""
    offset = 0
    for f in fields:
        if f.is_scalar:
            sz = f.size
            # Align to natural boundary
            if offset % sz != 0:
                offset += sz - (offset % sz)
            f.offset = offset
            offset += sz
        elif f.is_bool:
            f.offset = offset
            offset += 1
    # Pad header to 8-byte boundary so the variable section starts aligned.
    if offset % 8 != 0:
        offset += 8 - (offset % 8)
    return offset


def variable_fields(fields):
    return [f for f in fields if f.is_text or f.is_data]


def emit(schema_name, struct_name, schema_id, fields, header_len):
    var_fields = variable_fields(fields)
    has_var = bool(var_fields)
    needs_utf8 = any(f.is_text for f in fields)

    out = []
    a = out.append
    a('// Auto-generated by tools/capnp_dart_gen.py — DO NOT EDIT.')
    a(f'// Source: schemas/{schema_name}.capnp')
    a('// coverage:ignore-file')
    a('')
    if needs_utf8:
        a("import 'dart:convert';")
    a("import 'dart:typed_data';")
    a('')
    a(f'/// Zero-copy accessor into a {struct_name} Cap\'n Proto message.')
    a('///')
    a('/// The fixed-size scalar fields live in a packed header; any Text/Data')
    a('/// fields follow as a sequence of `[u32 length][bytes]` records in the')
    a('/// order they were declared.')
    a(f'class {struct_name}Reader {{')
    a(f'  /// Cap\'n Proto schema ID for {struct_name}.')
    a(f'  static const int schemaId = 0x{schema_id:04x};')
    a('')
    a('  final Uint8List _bytes;')
    a('')
    a(f'  {struct_name}Reader(this._bytes)')
    a("      : assert(_bytes.isNotEmpty, 'Empty Cap\\'n Proto buffer');")

    # Scalar / bool accessors
    for f in fields:
        a('')
        name = snake_to_camel(f.name)
        if f.is_bool:
            a(f'  bool get {name} =>')
            a(f'      _bytes.length > {f.offset} && (_bytes[{f.offset}] & 0x01) != 0;')
        elif f.is_scalar:
            dart_type, suffix, sz = SCALAR_TYPES[f.capnp_type]
            if sz == 1 and f.capnp_type == 'UInt8':
                a(f'  int get {name} =>')
                a(f'      _bytes.length > {f.offset} ? _bytes[{f.offset}] : 0;')
            else:
                a(f'  {dart_type} get {name} => _read{suffix}({f.offset});')
        elif f.is_text:
            a(f'  String get {name} => _readText({_var_offset_expr(f, var_fields)});')
        elif f.is_data:
            a(f'  Uint8List get {name} =>')
            a(f'      _readData({_var_offset_expr(f, var_fields)});')

    # Variable-section helpers
    if has_var:
        a('')
        a(f'  static const int _kHeaderLen = {header_len};')
        a('')
        for i, f in enumerate(var_fields):
            sym = _var_offset_sym(f)
            if i == 0:
                a(f'  int {sym}() => _kHeaderLen;')
            else:
                prev = var_fields[i - 1]
                prev_sym = _var_offset_sym(prev)
                a(f'  int {sym}() => {prev_sym}() + 4 + _readUint32({prev_sym}());')

    # Fixed read helpers — only emit those actually used.
    # Use the Dart-style suffix from SCALAR_TYPES[1] (e.g. 'Uint64', not 'UInt64').
    # UInt8 fields are read inline as `_bytes[offset]`, so the helper is never
    # referenced — exclude it from emission to avoid an unused_element lint.
    used_suffixes = {
        SCALAR_TYPES[f.capnp_type][1] for f in fields
        if f.is_scalar and f.capnp_type != 'UInt8'
    }
    if any(f.is_text or f.is_data for f in fields):
        used_suffixes.add('Uint32')
    helper_emitters = {
        'Float32': _h_float32,
        'Float64': _h_float64,
        'Uint8':   _h_uint8,
        'Uint16':  _h_uint16,
        'Uint32':  _h_uint32,
        'Uint64':  _h_uint64,
        'Int8':    _h_int8,
        'Int16':   _h_int16,
        'Int32':   _h_int32,
        'Int64':   _h_int64,
    }
    for suffix in ('Float32', 'Float64', 'Uint8', 'Uint16', 'Uint32', 'Uint64',
                   'Int8', 'Int16', 'Int32', 'Int64'):
        if suffix in used_suffixes:
            a('')
            a(helper_emitters[suffix]())

    if any(f.is_text for f in fields):
        a('')
        a('  String _readText(int offset) {')
        a('    if (_bytes.length < offset + 4) return \'\';')
        a('    final len = _readUint32(offset);')
        a('    final start = offset + 4;')
        a('    if (len == 0 || _bytes.length < start + len) return \'\';')
        a('    return utf8.decode(_bytes.sublist(start, start + len));')
        a('  }')

    if any(f.is_data for f in fields):
        a('')
        a('  Uint8List _readData(int offset) {')
        a('    if (_bytes.length < offset + 4) return Uint8List(0);')
        a('    final len = _readUint32(offset);')
        a('    final start = offset + 4;')
        a('    if (len == 0 || _bytes.length < start + len) return Uint8List(0);')
        a('    return Uint8List.sublistView(_bytes, start, start + len);')
        a('  }')

    a('}')
    a('')

    # Builder
    a(f'/// Builds a {struct_name} Cap\'n Proto payload.')
    a(f'class {struct_name}Builder {{')
    a('  static Uint8List build({')
    for f in fields:
        name = snake_to_camel(f.name)
        if f.is_bool:
            a(f'    required bool {name},')
        elif f.is_scalar:
            dart_type, _, _ = SCALAR_TYPES[f.capnp_type]
            a(f'    required {dart_type} {name},')
        elif f.is_text:
            a(f'    required String {name},')
        elif f.is_data:
            a(f'    required Uint8List {name},')
    a('  }) {')

    if has_var:
        # Compute total length first
        for f in var_fields:
            name = snake_to_camel(f.name)
            if f.is_text:
                a(f'    final {name}Bytes = utf8.encode({name});')
        parts = [str(header_len)]
        for f in var_fields:
            name = snake_to_camel(f.name)
            if f.is_text:
                parts.append('4')
                parts.append(f'{name}Bytes.length')
            else:  # data
                parts.append('4')
                parts.append(f'{name}.length')
        a(f'    final total = {" + ".join(parts)};')
        a('    final buf = Uint8List(total);')
    else:
        a(f'    final buf = Uint8List({header_len});')

    a('    final bd = ByteData.sublistView(buf);')

    # Write fixed scalars
    for f in fields:
        name = snake_to_camel(f.name)
        if f.is_bool:
            a(f'    bd.setUint8({f.offset}, {name} ? 1 : 0);')
        elif f.is_scalar:
            _, suffix, _ = SCALAR_TYPES[f.capnp_type]
            if suffix in ('Uint8', 'Int8'):
                a(f'    bd.set{suffix}({f.offset}, {name});')
            else:
                a(f'    bd.set{suffix}({f.offset}, {name}, Endian.little);')

    # Write variable section
    if has_var:
        a(f'    int p = {header_len};')
        for f in var_fields:
            name = snake_to_camel(f.name)
            if f.is_text:
                src = f'{name}Bytes'
            else:
                src = name
            a(f'    bd.setUint32(p, {src}.length, Endian.little);')
            a('    p += 4;')
            a(f'    buf.setRange(p, p + {src}.length, {src});')
            a(f'    p += {src}.length;')

    a('    return buf;')
    a('  }')
    a('}')
    a('')

    return '\n'.join(out)


def _var_offset_sym(f):
    return f'_{snake_to_camel(f.name)}Offset'


def _var_offset_expr(f, var_fields):
    return f'{_var_offset_sym(f)}()'


# Helper-emitter functions for the Reader's read helpers.
def _h_float32():
    return ('  double _readFloat32(int offset) {\n'
            '    if (_bytes.length < offset + 4) return 0.0;\n'
            '    return ByteData.sublistView(_bytes).getFloat32(offset, Endian.little);\n'
            '  }')


def _h_float64():
    return ('  double _readFloat64(int offset) {\n'
            '    if (_bytes.length < offset + 8) return 0.0;\n'
            '    return ByteData.sublistView(_bytes).getFloat64(offset, Endian.little);\n'
            '  }')


def _h_uint8():
    return ('  int _readUint8(int offset) {\n'
            '    if (_bytes.length <= offset) return 0;\n'
            '    return _bytes[offset];\n'
            '  }')


def _h_uint16():
    return ('  int _readUint16(int offset) {\n'
            '    if (_bytes.length < offset + 2) return 0;\n'
            '    return ByteData.sublistView(_bytes).getUint16(offset, Endian.little);\n'
            '  }')


def _h_uint32():
    return ('  int _readUint32(int offset) {\n'
            '    if (_bytes.length < offset + 4) return 0;\n'
            '    return ByteData.sublistView(_bytes).getUint32(offset, Endian.little);\n'
            '  }')


def _h_uint64():
    return ('  int _readUint64(int offset) {\n'
            '    if (_bytes.length < offset + 8) return 0;\n'
            '    return ByteData.sublistView(_bytes).getUint64(offset, Endian.little);\n'
            '  }')


def _h_int8():
    return ('  int _readInt8(int offset) {\n'
            '    if (_bytes.length <= offset) return 0;\n'
            '    return ByteData.sublistView(_bytes).getInt8(offset);\n'
            '  }')


def _h_int16():
    return ('  int _readInt16(int offset) {\n'
            '    if (_bytes.length < offset + 2) return 0;\n'
            '    return ByteData.sublistView(_bytes).getInt16(offset, Endian.little);\n'
            '  }')


def _h_int32():
    return ('  int _readInt32(int offset) {\n'
            '    if (_bytes.length < offset + 4) return 0;\n'
            '    return ByteData.sublistView(_bytes).getInt32(offset, Endian.little);\n'
            '  }')


def _h_int64():
    return ('  int _readInt64(int offset) {\n'
            '    if (_bytes.length < offset + 8) return 0;\n'
            '    return ByteData.sublistView(_bytes).getInt64(offset, Endian.little);\n'
            '  }')


def main():
    ap = argparse.ArgumentParser(
        description='Generate Dart FFI bindings from Cap\'n Proto schemas')
    ap.add_argument('--schema-dir', required=True)
    ap.add_argument('--output-dir', required=True)
    ap.add_argument('--force', action='store_true',
                    help='Overwrite existing files (default: skip)')
    ap.add_argument('--capnpc', default='capnp',
                    help='Unused — kept for backward compat')
    args = ap.parse_args()

    schema_dir = Path(args.schema_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    schemas = sorted(schema_dir.glob('*.capnp'))
    if not schemas:
        print(f'No .capnp files found in {schema_dir}', file=sys.stderr)
        sys.exit(1)

    written = 0
    skipped = 0
    failed = 0
    for schema_path in schemas:
        schema_name = schema_path.stem
        out_path = output_dir / f'{schema_name}.capnp.dart'

        text = schema_path.read_text()
        parsed = parse_schema(text)
        if not parsed:
            print(f'  ! {schema_name}: failed to parse')
            failed += 1
            continue
        struct_name, schema_id, fields = parsed
        header_len = layout(fields)
        code = emit(schema_name, struct_name, schema_id, fields, header_len)

        if out_path.exists() and not args.force:
            print(f'  - {schema_name}: exists, skipping (use --force to overwrite)')
            skipped += 1
            continue

        out_path.write_text(code)
        print(f'  + {schema_name} -> {out_path} ({len(fields)} fields, header={header_len}B)')
        written += 1

    print(f'\nProcessed {len(schemas)} schemas: {written} written, '
          f'{skipped} skipped, {failed} failed')
    sys.exit(0 if failed == 0 else 1)


if __name__ == '__main__':
    main()
